name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Trass3r/setup-cpp@master
    - run: |
        sudo apt update && sudo apt install -y build-essential g++ clang lld texinfo libpython3-dev python3 ccache
    - uses: hendrikmuhs/ccache-action@v1.2
      with:
        max-size: 1G
        verbose: 1
    - name: build
      env:
        CC: 'ccache clang'
        CXX: 'ccache clang++'
        LD: 'ld.lld'
        CFLAGS: '-march=skylake -flto=thin -ffunction-sections -fdata-sections'
        CXXFLAGS: '-march=skylake -flto=thin -ffunction-sections -fdata-sections'
        LDFLAGS: '-fuse-ld=lld -Wl,--gc-sections -static-libgcc -static-libstdc++'
      run: |
        # --disable-unit-tests doesn't build
        # --with-intel_pt extra dep..
        # --enable-static --disable-interprocess-agent doesn't work with plugins
        ./configure --prefix=$(pwd)/install --disable-nls --disable-sim --disable-werror --enable-plugins --with-gdb --disable-tui --with-python=no
        make -j4
        make install-strip
    - name: create tarball
      run: cd install && tar cvapf "$GITHUB_WORKSPACE/binutils.tar.xz" *
    - uses: actions/upload-artifact@v3
      with:
        name: binutils
        path: binutils.tar.xz
